name: Compila y Genera PDF
on:
  push:
      branches:
        - main
jobs:
  compila:
    runs-on: ubuntu-latest
    steps:
      - name: Chequea el repositorio
        uses: actions/checkout@v4

      - name: Instalar .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Instalar dependencias
        run: dotnet restore      

      - name: Compilar el proyecto
        run: dotnet build --no-restore
   
  creap-PDF:
    strategy:
      matrix:
        node_version: ['18.x', '20.x']
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node_version }}

      - name: npm install, build and test
        run: |
          npm install
          npm run build --if-present